### ISSUE TITLE
What is it like being a creative in a smaller city?

### ISSUE THREAD

**Issue by wesbos** [cassiemc/ama#1]
Paris Ontario is cool little city - what is it like to be a creative in a smaller city versus something like Toronto?

**Comment by cassiemc** [comment]
The web is wide, so in some ways it is no different; because I work remotely on the web I still work with colleagues in different time zones and around the world, and I'm lucky to still maintain the scale of those opportunities, especially in terms of having a large global impact. This has a lot to do with at what point in my career I moved out here, though.

When I was starting out I found it important to be able to try lots of different paths to see what suited me and I'm not sure I would've found that variety of opportunities in Paris right away. It'd be hard to get a full-time paying job in Paris as a young designer right away (not impossible, but hard). I do think opportunities are always what you make of them – you can still do quirky photo projects, support local non-profits or work with other hungry local artists on collaborations – as long as you are thinking big, the sky's the limit. I've not been an independent contractor out here though, and the most successful countryside contractors I've seen tend to have both local and international clients.

Lastly, what I love about living in a small town is the impact I can have on local people's lives. I feel like I matter. In cities you make great connections too – great people are everywhere – but cities are so transient and I found the sets of people I met at events always coming and going. Out here, people have put down roots and they depend on each other more, whether because there is little else to do for company other than hang out on someone's porch or because towns are farther apart and snow / cars / money are all a little less predictable. I like feeling like I can help a community grow creatively and meaningfully.

**Comment by wesbos** [comment]
:+1: Awesome answer - thank you!
