### ISSUE TITLE
How important do you think it is for your career to write a book?

### ISSUE THREAD

**Issue by pearlchen** [cassiemc/ama#13]
(Right back at 'cha)

https://github.com/pearlchen/ama/issues/1

**Comment by cassiemc** [comment]
Lol @pearlchen your answer was great. I agree with all your reasons, except the one about having something you've made that is non-screen based is weirdly less important to me (weird because as a person who works in tech but doesn't necessarily like to use tech, that surprises me). I would only add that I think having a publication under the belt increases the credibility of your ideas with peers.
