### ISSUE TITLE
If you could read only one book for the rest of time, what would it be?

### ISSUE THREAD

**Issue by darrinhenein** [cassiemc/ama#3]

**Comment by cassiemc** [comment]
This is such a hard question for me because I make it a point to _never_ read the same book twice. I can tell you it would definitely not be a technical book, and probably not the Bible because I hear that's repetitive. It'd be a classic, with lovely imagery, amazingly written, that conjures up different ideas depending on where you're at in life. I'm going to have to go through my bookshelves and get back to you on this.

**Comment by cassiemc** [comment]
I'm going to go with the consolidated works of Nancy Drew.

**Comment by hannahkane** [comment]
Oooh...I re-read all of the original series last year, and put the best/weirdest stuff on Tumblr: http://wtfnancydrew.tumblr.com/.
