### ISSUE TITLE
How would you approach growing design culture in a company with one designer?

### ISSUE THREAD

**Issue by calvinhfcheng** [cassiemc/ama#5]
I've been working at a growing startup as an 'embedded' designer (thanks for the essay, btw) for the past two years and I've been having challenges scaling design beyond myself (team is at 17 people now). It's not that the company doesn't see the importance of design, but I'm a believer that the design mindset shouldn't be solely owned by the designer or designers of a given company—everyone should have it. 

Design in technology doesn't really have a defined shape. The challenge I'm having is it's hard to convey both the nuances and broadness of qualitative, strategic thinking down to the importance of craft and beauty in design.

What's the first step? How does it start? Am I asking too much of them?

**Comment by cassiemc** [comment]
Mostly I have questions for you.
- Is there a champion of design high up in the company? In my experience this has made a huge difference.
- 'Design' is such a broad term and it's hard for people not experience with it to grasp all the different facets. Can you help people learn the difference between product design, UX, UI, etc?
- What have you tried already? When I worked in healthcare I helped revive a lunch and learn series that was nice because it covered all sorts of different topics, not just design, so it involved everyone. It was important that it was also fun; we had sessions where we built things together out of cardboard or tried out improv. A few people planned it together and that gave it life. Anything where you can engage people as co-owners is a positive step.

I'm not sure what business your startup is in, but 1:17 is kind of a scary ratio. That said, you can (and should!) enlist people with other job titles to be your allies in this. You will need help! 

Other things I might try are focusing on one project as a case study of what design can do then shouting about that case study every chance you get. Also, sharing articles and resources is always good and just keeps the door open for people to come and talk to you about design. You'll probably find that people are already interested (it's such a pervasive part of culture right now) but just don't know where to start.

It's going to be really hard though for you – one person – to teach non-designers to start delivering designs (if that's what you mean by scaling design within your company) so I'd engage with a leader within your company and at least ask for an intern!
