### ISSUE TITLE
How and when did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [cassiemc/ama#9]

**Comment by cassiemc** [comment]
Well, I never did get into programming! I love programmers, have very little patience for it myself.

I do an eensy bit of frontend stuff. I built some html sites in highschool with wysiwyg editors, learned a bit of actionscript for animations at my first job, and despite my protests my husband finally sat me down in 2009 to teach me css with scraps of paper on the floor. I have built a few sites myself since then, nothing fancy, but those experiences gave me a basic understanding that I need to design things well.
